services:
  - type: web
    name: ai-resume-analyzer
    runtime: python
    buildCommand: "pip install -r requirements.txt && python backend/manage.py collectstatic --noinput && python backend/manage.py migrate"
    startCommand: "gunicorn --chdir backend config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: resume-analyzer-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: resume-analyzer-db